### ISSUE TITLE
sourcemap has wrong location for .cljs files

### ISSUE THREAD

**Issue by mbertheau** [boot-clj/boot-cljs#136]
Symptom: Chrome tries to load a cljs file from `/static/cljs-js/dashboard/product_form.out/product_form/product_form.out/product_form/when.cljs`, when the correct location is `/static/cljs-js/dashboard/product_form.out/product_form/when.cljs`.

I have `:compiler-options {:asset-path "/static/cljs-js/dashboard/product_form.out"}` in `product_form.cljs.edn`.

`when.js.map` has `"sources":["product_form.out\/product_form\/when.cljs"]` in it.

**Comment by onetom** [comment]
`(task-options! cljs {:source-map true})` is the default behaviour, yet when specified explicitly, it behaves differently, because an extra `:source-map-path` key is added to the ClojureScript compiler configuration.

This is where it happens:
https://github.com/adzerk-oss/boot-cljs/blob/master/src/adzerk/boot_cljs/middleware.clj#L113-L116

We just had a conversation about this yesterday on #hoplon
https://clojurians-log.clojureverse.org/hoplon/2016-09-13.html

The workaround currently is just to omit `:source-map` when you would set it to `true`.

**Comment by mbertheau** [comment]
The workaround works for me. Thanks @onetom!

I don't know enough to say whether there's still a bug here or not, so I'll leave this issue open for someone else to decide.

**Comment by Deraen** [comment]
Interesting. Explicitly enabling should definitely work if the default (nil) works. I guess we don't need to set the path when using none optimization then, will have to check if it is needed with optimizations.

https://github.com/adzerk-oss/boot-cljs/blob/master/src/adzerk/boot_cljs/middleware.clj#L105

**Comment by borkdude** [comment]
Example project where this also applies: https://github.com/borkdude/boot-source-maps-issue/
Removing `:source-maps true` resolves the issue.

**Comment by kommen** [comment]
This also applied for me having the `:source-map` option in the `.cljs.edn` file. Removing it from there also worked around the issue.

**Comment by thos37** [comment]
This is only a problem with more recent CLJS.  If I use an older one like 1.7.228, the problem also goes away.
```
                  ;[org.clojure/clojurescript "1.9.495"]
                  [org.clojure/clojurescript "1.7.228"]
```

**Comment by thos37** [comment]
What is the purpose of the `:source-map-path` entry?  https://github.com/boot-clj/boot-cljs/blob/master/src/adzerk/boot_cljs/middleware.clj#L116  
Removing that line fixed the problem for me in all scenarios with both `:optimizations` `:none` and `:simple` and with both CLJS 1.9.495 and 1.7.228.
